mysite/grader/urls.py
from django.urls import path

from . import views

app_name = 'grader'

urlpatterns = [
    path('', views.loging, name='login'),
    path('idex/', views.index, name='index'),
    path('<int:question_id>/', views.question, name='question'),
    path('<int:question_id>/essay<int:essay_id>/', views.essay, name='essay'),
    path('userlogin/',views.userlogin, name='userlogin'),
    path('logout/',views.userlogout, name='logout'),
    path('register/',views.register,name='register'),
    path('uinfo/',views.userInfo,name='userInfo'),
    path('uinfo/ucentre/',views.userCentre, name='userCentre'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('about/',views.about,name='about'),
    path('downloadfile/<int:doc_id>', views.download_file, name='download_file'),
    path('file2txt/', views.file2txt, name='file2txt'),
    path('chinese/', views.chinese, name='chinese'),
    path('zhessay<int:chinese_id>/', views.zhessay, name='zhessay')
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('', include('grader.urls')),#system management
    path('admin/', admin.site.urls),#backgroud management
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/grader/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import Essay
from .models import RawEssays
from .models import Chinese


# 用户注册表单
class UserCustomRegister(UserCreationForm):
    name = forms.CharField(required=False, max_length=50)
    cate = forms.BooleanField(required=True)
    faculty = forms.CharField(required=True, max_length=20)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email',
                  'name', 'cate', 'faculty')

# 用户修改信息表单
class UserCustomChange(UserChangeForm):
    name = forms.CharField(required=False, max_length=50)

    class Meta:
        model = User
        fields = ('email', 'password', 'name')

class UserRegister(UserCreationForm):
    name = forms.CharField(required=False, max_length=50)
    cate = forms.BooleanField(required=True)
    faculty = forms.CharField(required=True, max_length=20)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'name', 'cate', 'faculty']

class UserUpdate(UserChangeForm):
    name = forms.CharField(required=False, max_length=50)

    class Meta:
        model = User
        fields = ['email', 'password', 'name']

class AnswerForm(forms.ModelForm):
    answer = forms.CharField(label='作文内容', max_length=100000,
                             widget=forms.Textarea(attrs={'rows': 5, 'placeholder': "请输入作文内容"}))

    class Meta:
        model = Essay
        fields = ['answer']

class RawEssaysForm(forms.ModelForm):
    class Meta:
        model = RawEssays
        fields = ('file',)

        widgets = {
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1].lower()
        if ext not in ["txt", "doc", "docx", "pdf", "jpg", "jpeg", "png"]:
            raise forms.ValidationError("请上传txt, doc/docx, pdf, jpg, jpeg 以及 png 格式的文件")
        return file

class ChineseForm(forms.ModelForm):
    title = forms.CharField(label='作文题目', max_length=100,
                              widget=forms.Textarea(attrs={'rows': 1, 'placeholder': "请输入作文内容"}))
    content = forms.CharField(label='作文内容', max_length=100000,
                              widget=forms.Textarea(attrs={'rows': 10, 'placeholder': "请输入作文内容"}))

    class Meta:
        model = Chinese
        fields = ['title', 'content']

mysite/templates/about.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
    -关于
{% endblock %}

{% block css %}
    {% static 'css/about.css' %}
{% endblock %}
{% block aboutHighlight %}
    active
{% endblock %}
{% block main_block %}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <div class="row">

        <div class="col-10">
            <div class="alert alert-success text-center " role="alert">
                AES作文评分系统，由北京师范大学人工智能学院邵子轩设计，仅供学习参考，更多内容可下载相关资料文件查看
            </div>

            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100"
                             src="{% static 'images/about1.png' %}?auto=yes&bg=777&fg=555&text=First slide"
                             alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100"
                             src="{% static 'images/minilogo.png' %}?auto=yes&bg=666&fg=444&text=Second slide"
                             width="263"
                             height="450"
                             alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100"
                             src="{% static 'images/about2.jpg' %}?auto=yes&bg=555&fg=333&text=Third slide"
                             width="263"
                             height="450"
                             alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <br>
        </div>
        <div class="col-2">
            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">相关文件下载
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    {% for doc in docList %}
                        <a href="{% url 'grader:download_file' doc.id %}">{{ doc.file_name }}</a><br>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keyword" content="{% block keyword %}BASE_HTML{% endblock %}">
    <meta name="description" content="{% block description %}BASE_HTML{% endblock %}">
    <meta name="author" content="szxgraduate">
    <link rel="icon" href="{% static 'images/AES.ico' %}">
    <title>AES作文评分系统
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% block css %}
    {% endblock css %}">
</head>

<body>
{% block top %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <img src="{% static 'images/logo.png' %}"
         width="33" height="33" class="d-inline-block align-top" alt="">&nbsp;&nbsp;
    <a class="navbar-brand" href="#">AES作文评分系统</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item  {% block indexHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'grader:index' %}">英文作文评分 <span class="sr-only">(current)</span></a>
            </li>
{#            <li class="nav-item  {% block insindexHighlight %}{% endblock %}">#}
{#                <a class="nav-link" href="{% url 'Lab:ins_index' %}">仪器列表 <span class="sr-only">(current)</span></a>#}
{#            </li>#}
{#            <li class="nav-item  {% block labHighlight %}{% endblock %}">#}
{#                <a class="nav-link" href="{% url 'Lab:lab' %}">实验室列表<span class="sr-only">(current)</span></a>#}
{#            </li>#}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'grader:chinese' %}">中文作文评分 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% block userHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'grader:userInfo' %}">个人中心</a>
            </li>
            <li class="nav-item {% block aboutHighlight %}{% endblock %}">
                <a class="nav-link disabled" href="{% url 'grader:about' %}">关于</a>
            </li>
        </ul>

{#        <form style="margin-right: 50px" class="form-inline my-2 my-lg-0" action="{% url 'Lab:medicineSearch' %}"#}
{#              method="POST">#}
{#            {% csrf_token %}#}
{#            <input name='keyword' class="form-control mr-sm-2" type="text" placeholder="请输入要查询的作文" aria-label="Search">#}
{#            <div class="form-row align-items-center">#}
{#                <div class="col-auto my-1">#}
{#                    <label class="mr-sm-2 sr-only" for="inlineFormCustomSelect">Preference</label>#}
{#                    <select name='searchType' class="custom-select mr-sm-2" id="inlineFormCustomSelect">#}
{#                        <option selected>所有</option>#}
{#                        <option value="name">药品名</option>#}
{#                        <option value="number">药品编号</option>#}
{#                    </select>#}
{#                </div>#}
{#            </div>&nbsp;&nbsp;&nbsp;&nbsp;#}
{#            <button style="width: 100px" class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>#}
{#        </form>#}

        {% if user.is_authenticated %}
            <a href="{% url 'grader:logout' %}">
                <button style="width: 150px" class="btn btn-primary">{{ user.username }}, 登出</button>
            </a>
            </div>
        {% else %}
            <a href="{% url 'grader:login' %}">
                <button style="width: 100px" class="btn btn-primary">登录</button>
            </a>
            </div>
        {% endif %}
</nav>
{% endblock top %}

<main role="main" class="container">
    {% block main_block %}
    {% endblock %}

</main>
<footer class="footer">
    <div class="copyright" style="text-align: center">
        <p>
            <span>Copyright (C). create by BHML 2024, All Rights Reserved</span>&nbsp;&nbsp;
            <a href="/admin">管理员入口</a>
        </p>
    </div>
</footer>

<!-- Bootstrap core JavaScript  -->
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

mysite/templates/borrowHistory.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
    -借用历史
{% endblock %}

{% block css %}
    {% static 'css/borrowHistory.css' %}
{% endblock %}
{% block main_block %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {% if successInfo %}
            <div class="text-center welcomeSlogan"><strong>{{ successInfo }}</strong></div>
        {% elif failedInfo %}
            <div class="text-center welcomeSlogan"><strong>{{ failedInfo }}</strong></div>
        {% else %}
            <div class="text-center welcomeSlogan"><strong>欢迎查看药品借用历史记录</strong></div>
        {% endif %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="col-md-12">
        <div id="table-responsive">
            <table class="table table-hover">
                <thead class="thead-light">
                <tr>
                    <th scope="col">序号</th>
                    <th scope="col">药品</th>
                    <th scope="col">药品使用量</th>
                    <th scope="col">实验室</th>
                    <th scope="col">取用时间</th>
                    <th scope="col">已用天数</th>
                </tr>
                </thead>

                <tbody class="no_underline">
                {% if MedicineList %}
                    {% for medicine,borrowInfo,borrowTime in MedicineList %}
                        <tr class="table">
                            <th class="text-dark" scope="row">{{ forloop.counter }}</th>
                            <td class="text-dark">{{ borrowInfo.medicine }}</td>
                            <td class="text-dark">{{ borrowInfo.medicineUsedNum }} g</td>
                            <td class="text-dark">{{ borrowInfo.lab }}</td>
                            <td class="text-dark">{{ borrowInfo.boDate }}</td>
                            <td class="text-dark">{{ borrowTime }}天</td>
                        </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

mysite/templates/changePassword.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
    -修改密码
{% endblock %}

{% block passHighlight %}
    active
{% endblock %}
{% block css %}
    {% static 'css/userCentre.css' %}
{% endblock %}

{% block main_block %}

    {% if changepasswordForm.errors %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">密码修改失败</h4>
            <p>{{ changepasswordForm.errors }}</p>
            <hr>
            <p class="mb-0">如要修改请注意以上的错误</p>
        </div>
    {% endif %}
    <div>

        <form class="form-group" action="" method="POST" style="margin-top: 3%;margin-left: 30%;width: 40%">
            <h2>修改密码</h2>
            <hr/>
            {% csrf_token %}
            <p><label for="id_old_password">旧密码:</label>
                <input type="password" name="old_password" autofocus=""
                       required="" id="id_old_password"></p>
            <p><label for="id_new_password1">新密码:</label>
                <input type="password" name="new_password1" required=""
                       id="id_new_password1"> <span class="helptext"></span>
            </p>
            注意：你的密码必须包含至少 8 个字符,且不能全部为数字。
            <p></p>
            <p><label for="id_new_password2">新密码确认:</label>
                <input type="password" name="new_password2" required="" id="id_new_password2"></p>
            <button class="btn btn-primary" type="submit" style="width: 100%">确定</button>
        </form>
    </div>

{% endblock %}

mysite/templates/login.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>用户登录-AES作文评分系统</title>
</head>
<style type="text/css">
    body{
        background: url("../static/images/AES.png")center center fixed;
        -webkit-background-size: cover;
        -o-background-size: cover;
        background-size: 100% 100%;
    }

    #neon-btn{
        display: flex;
        align-items: center;
        justify-content: space-around;
        margin-top: 20%;
    }

    .btn{
        border: 1px solid;
        background-color: transparent;
        text-transform: uppercase;
        font-size: 28px;
        padding: 10px 20px;
        font-weight: 300;
    }

    .one{
        color: #4cc9f0;

    }

    .three{
        color: #b9e769;
    }

    .btn:hover{
        color: white;
        border: 0;
    }

    .btn a{
        color: orange;
    }

    .btn a:hover{
        color: white;
    }

    .one:hover{
        background-color: #4cc9f0;
        -webkit-box-shadow: 10px 10px 99px 6px rgba(76,201,240,1);
        -moz-box-shadow: 10px 10px 99px 6px rgba(185,231,105,1);
        box-shadow: 10px 10px 99px 6px rgba(185,231,105,1);
    }

    .three:hover{
        background-color: #b9e769;
        -webkit-box-shadow: 10px 10px 99px 6px rgba(185,231,105,1);
        -moz-box-shadow: 10px 10px 99px 6px rgba(185,231,105,1);
        box-shadow: 10px 10px 99px 6px rgba(185,231,105,1);
    }
    h1{
        text-align: center;
        margin-top: 10%;
        color: white;
        font-size: xxx-large;
        font-family: 楷体;
    }
</style>
<body>
    <h1>欢迎登录AES作文评分系统</h1>
<div id="neon-btn">
    <button class="btn one"><a style="text-decoration-line: unset;font-weight: bolder" href="/userlogin/">用户登录</a></button>
    <button class="btn three"><a style="text-decoration-line: unset;font-weight: bolder" href="/admin/" >管理员登录</a></button>
</div>
</body>
</html>

mysite/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
 - 注册
{% endblock %}
    {% static 'css/register.css' %}
{% block css %}

{% endblock %}

{% block main_block %}

    {% if registerForm.errors %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">注册出现问题了哦！</h4>
            <p>{{ registerForm.errors }}</p>
            <hr>
            <p class="mb-0">请再次注册！</p>
        </div>
    {% endif %}

    <script type="text/javascript">
        function name() {
            var username = document.getElementById("id_username");
            var usernametext = username.value;
            //验证字符串符合规则
            var patt = /^\d{8}$/;
            /*test方法用于测试字符串是否匹配规则*/
            if (patt.test(usernametext)) {

            } else {
                alert("学号不合法！")
            }
        }
    </script>

    <form class="form-group registerForm" action="" method="POST" style="width: 40%;margin-left: 30%">
        {% csrf_token %}
        <p>
            <label for="id_username">学号:</label>
            <input class="form-control" type="text" name="username" maxlength="8" autofocus required
                   id="id_username" value="">
            <small class="form-text text-muted">必填! 8位学号</small>
        </p>
        <p>
            <label for="id_nickyName">昵称:</label>
            <input class="form-control" type="text" name="nickyName" maxlength="50"
                   id="id_nickyName">
        </p>
        <p>
            <label for="id_password1">密码:</label>
            <input class="form-control" type="password" name="password1" required id="id_password1">
            <small class="form-text text-muted">
                你的密码必须包含至少 8 个字符!
            </small>
        </p>
        <p><label for="id_password2">密码确认:</label>
            <input class="form-control" type="password" name="password2" required id="id_password2">
            <small class="form-text text-muted">为了校验，请输入与上面相同的密码。</small>
        </p>
        <p>
            <label for="id_email">电子邮件地址:</label>
            <input class="form-control" type="email" name="email" maxlength="254" id="id_email"></p>

        <p>
            <label class="form-check-label" for="id_cate">是否学生:</label>
            <input type="checkbox" name="cate" required id="id_cate">
            <small class="form-text text-muted">勾选表明为学生用户，不勾选为教师用户</small>
        </p>
        <p>
            <label for="id_faculty">学院:</label>
            <input class="form-control" type="text" name="faculty" maxlength="20" required id="id_faculty">
            <small class="form-text text-muted">请输入您的学院</small>
        </p>
        <button class="btn btn-primary" type="submit" onclick="name()" style="width: 100%">立即注册</button>
    </form>
    <br/>
{% endblock %}

mysite/templates/userCentre.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
    -用户中心
{% endblock %}

{% block css %}
    {% static 'css/userCentre.css' %}
{% endblock %}
{% block main_block %}
    {% if changeForm.errors %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">修改信息中出现问了哦！</h4>
            <p>{{ changeForm.errors }}</p>
            <hr>
            <p class="mb-0">如要修改请注意以上的错误：</p>
        </div>
    {% endif %}
    <div>
        <form class="form-group" action="" method="POST" style="width: 40%;margin-left: 30%;margin-top: 3%">
            <h2>修改个人信息</h2>
            <hr>
            {% csrf_token %}
            <div class="form-group row">
                <label for="id_username" class="col-sm-3 col-form-label">用户名:</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control-plaintext" id="staticUsername"
                           value="{{ currentUser.username }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="id_name" class="col-sm-3 col-form-label">昵称:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="name" maxlength="50" id="id_name"
                           placeholder="{{ currentUser.commonuser.nickyName }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="id_cate" class="col-sm-3 col-form-label">用户类型:</label>
                <div class="col-sm-9">
                    {% if currentUser.commonuser %}
                        <input type="text" readonly class="form-control-plaintext" id="staticCate"
                               value="学生">
                    {% else %}
                        <input type="text" readonly class="form-control-plaintext" id="staticCate"
                               value="教师">
                    {% endif %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_faculty" class="col-sm-3 col-form-label">院系:</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control-plaintext" id="staticFaculty"
                           value="{{ currentUser.commonuser.faculty }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="id_email" class="col-sm-3 col-form-label">邮箱:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="email" name="email" maxlength="254" id="id_email"
                           placeholder="{{ currentUser.email }}">
                </div>
            </div>
            <button class="btn btn-primary" type="submit" style="width: 100%">保存</button>
        </form>
    </div>

{% endblock %}

mysite/templates/userlogin.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
 - 用户登录
{% endblock %}

{% block css %}
    {% static 'css/login.css' %}
{% endblock %}

{% block top %}
    <a href="{% url 'grader:login' %}">
        <button style="width: 150px" class="btn btn-primary fixed-top" >返回初始登录页</button>
    </a>
{% endblock %}

{% block main_block %}
    {% if error %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <div class="text-center welcomeSlogan"><strong>{{ error }}</strong></div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="row">
        <form class="form-signin" action="" method="POST">
            {% csrf_token %}
            <div class="text-center mb-4">
                <img class="mb-4" src="{% static 'images/AES.png' %}" alt="" width="106" height="106">
                <h1 class="h3 mb-3 font-weight-normal">AES作文评分系统</h1>
                <p> 欢迎登录,未注册请先 <a href="{% url 'grader:register' %}">立即注册</a></p>

            </div>

            <div class="form-label-group">
                <input name="username" id="inputUserName" class="form-control" placeholder="请输入学号" required=""
                       autofocus="" type="text">
                <label for="inputUserName">学号</label>
            </div>

            <div class="form-label-group">
                <input name="password" id="inputPassword" class="form-control" placeholder="请输入密码" required=""
                       type="password">
                <label for="inputPassword">密码</label>
            </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        </form>
    </div>
{% endblock %}

mysite/templates/usr_info.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %} - 个人中心
{% endblock %}

{% block css %}
    {% static 'css/usr_info.css' %}
{% endblock %}

{% block main_block %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <section id="content" class="clearfix">
        <section class="light-buttons">
            <div class="right">
                <h1 class="dark-header">个人中心</h1>
                <a href="{% url 'grader:userCentre' %}" class="button lightbg-blue clearfix"><span>个人信息</span>
                    <div class="icon">
                        <div class="arrow"></div>
                    </div>
                </a>
{#                 <a href="{% url 'Lab:borrowHistory' %}" class="button lightbg-pink clearfix"><span>借阅药品历史</span>#}
{#                <div class="icon">#}
{#                    <div class="arrow"></div>#}
{#                </div>#}
{#            </a> <a href="{% url 'Lab:borrowInsHistory' %}" class="button lightbg-green clearfix"><span>借阅仪器历史</span>#}
{#                <div class="icon">#}
{#                    <div class="arrow"></div>#}
{#                </div>#}
{#            </a>#}
                <a href="{% url 'grader:changePassword' %}" class="button lightbg-orange clearfix"><span>修改密码</span>
                <div class="icon">
                    <div class="arrow"></div>
                </div>
            </a>
            </div>
        </section>
    </section>
{% endblock %}