mysite/grader/urls.py
from django.urls import path

from . import views

app_name = 'grader'

urlpatterns = [
    path('', views.loging, name='login'),
    path('idex/', views.index, name='index'),
    path('<int:question_id>/', views.question, name='question'),
    path('<int:question_id>/essay<int:essay_id>/', views.essay, name='essay'),
    path('userlogin/',views.userlogin, name='userlogin'),
    path('logout/',views.userlogout, name='logout'),
    path('register/',views.register,name='register'),
    path('uinfo/',views.userInfo,name='userInfo'),
    path('uinfo/ucentre/',views.userCentre, name='userCentre'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('about/',views.about,name='about'),
    path('downloadfile/<int:doc_id>', views.download_file, name='download_file'),
    path('file2txt/', views.file2txt, name='file2txt'),
    path('chinese/', views.chinese, name='chinese'),
    path('zhessay<int:chinese_id>/', views.zhessay, name='zhessay')
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('', include('grader.urls')),#system management
    path('admin/', admin.site.urls),#backgroud management
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/grader/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class CommonUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField('用户名',blank=True,max_length=50)
    cate = models.BooleanField('是否学生',default=False)
    faculty = models.CharField('院系',blank=True,max_length=20,default='undefine')

    class Meta:
        verbose_name = '用户信息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.user)

class Question(models.Model):
    """ A model of the 8 questions. """
    question_title = models.TextField(max_length=100000, verbose_name='英文作文题目')
    set = models.IntegerField(unique=True, verbose_name='作文集序号')
    min_score = models.IntegerField(verbose_name='最低分')
    max_score = models.IntegerField(verbose_name='作文分值')

    def update_content(self):
        if len(str(self.question_title)) > 35:
            return '{}...'.format(str(self.question_title)[0:35])
        else:
            return self.question_title
    update_content.short_description = '英文作文题目'

    class Meta:
        verbose_name = '英文作文题库'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.set)

class Essay(models.Model):
    """ Essay to be submitted. """
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='作文题号')
    content = models.TextField(max_length=100000, verbose_name='作文内容')
    score = models.IntegerField(null=True, blank=True, verbose_name='作文得分')
    submitter = models.IntegerField(null=False, verbose_name='作文提交者')
    date = models.DateTimeField('上传时间', auto_now_add=True)

    def __str__(self):
        return str(self.content)

    class Meta:
        verbose_name = '用户提交英文作文'
        verbose_name_plural = verbose_name

class Chinese(models.Model):
    title = models.TextField(max_length=100, verbose_name='作文题目')
    content = models.TextField(max_length=100000, verbose_name='作文内容')
    logic_score = models.IntegerField(null=True, blank=True, verbose_name='连贯度')
    topic_score = models.IntegerField(null=True, blank=True, verbose_name='切题度')
    submitter = models.IntegerField(null=False, verbose_name='作文提交者')
    date = models.DateTimeField('上传时间', auto_now_add=True)

    def __str__(self):
        return str(self.content)

    class Meta:
        verbose_name = '用户提交中文作文'
        verbose_name_plural = verbose_name

class Doc(models.Model):
    file_name = models.CharField('文件名字', max_length=50)
    file_obj = models.FileField('文件', upload_to='files/')
    upload_time = models.DateTimeField('上传时间', auto_now_add=True)

    def __str__(self):
        return self.file_name

    class Meta:
        db_table = 'doc'
        verbose_name = '相关文件信息表'
        verbose_name_plural = verbose_name

class RawEssays(models.Model):
    file_name = models.FileField('文件名', max_length=50)
    file = models.FileField('文件', upload_to='RawEssays/')
    upload_time = models.DateTimeField('上传时间', auto_now_add=True)

    def __str__(self):
        return self.file_name

    class Meta:
        db_table = 'RawEssays'
        verbose_name = '上传作文文件'
        verbose_name_plural = verbose_name

mysite/grader/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import Essay
from .models import RawEssays
from .models import Chinese


# 用户注册表单
class UserCustomRegister(UserCreationForm):
    name = forms.CharField(required=False, max_length=50)
    cate = forms.BooleanField(required=True)
    faculty = forms.CharField(required=True, max_length=20)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email',
                  'name', 'cate', 'faculty')

# 用户修改信息表单
class UserCustomChange(UserChangeForm):
    name = forms.CharField(required=False, max_length=50)

    class Meta:
        model = User
        fields = ('email', 'password', 'name')

class UserRegister(UserCreationForm):
    name = forms.CharField(required=False, max_length=50)
    cate = forms.BooleanField(required=True)
    faculty = forms.CharField(required=True, max_length=20)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'name', 'cate', 'faculty']

class UserUpdate(UserChangeForm):
    name = forms.CharField(required=False, max_length=50)

    class Meta:
        model = User
        fields = ['email', 'password', 'name']

class AnswerForm(forms.ModelForm):
    answer = forms.CharField(label='作文内容', max_length=100000,
                             widget=forms.Textarea(attrs={'rows': 5, 'placeholder': "请输入作文内容"}))

    class Meta:
        model = Essay
        fields = ['answer']

class RawEssaysForm(forms.ModelForm):
    class Meta:
        model = RawEssays
        fields = ('file',)

        widgets = {
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1].lower()
        if ext not in ["txt", "doc", "docx", "pdf", "jpg", "jpeg", "png"]:
            raise forms.ValidationError("请上传txt, doc/docx, pdf, jpg, jpeg 以及 png 格式的文件")
        return file

class ChineseForm(forms.ModelForm):
    title = forms.CharField(label='作文题目', max_length=100,
                              widget=forms.Textarea(attrs={'rows': 1, 'placeholder': "请输入作文内容"}))
    content = forms.CharField(label='作文内容', max_length=100000,
                              widget=forms.Textarea(attrs={'rows': 10, 'placeholder': "请输入作文内容"}))

    class Meta:
        model = Chinese
        fields = ['title', 'content']

mysite/grader/views.py
import datetime
import json
import requests
from dateutil.relativedelta import relativedelta
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage, EmptyPage
from django.db import connection
from django.db.models import Q, Count
from django.http import HttpResponse, FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.encoding import escape_uri_path

from .models import *
from .forms import AnswerForm,UserCustomRegister,UserCustomChange,RawEssaysForm,ChineseForm

from .utils.model import *
from .utils.helpers import *
from .utils.file2text import *
import glob

import os
current_path = os.path.abspath(os.path.dirname(__file__))

# Create your views here.
def loging(request):
    return render(request,'login.html')

def userlogin(request):
    if request.method == 'POST':
        user = authenticate(request,username=request.POST['username'],password=request.POST['password'])
        if user is None:
            return render(request,'userlogin.html',{'error':'用户不存在或密码错误!'})
        else:
            login(request, user)
            return redirect('grader:index')
    else:
        return render(request,'userlogin.html')

def userlogout(request):
    logout(request)
    return redirect('grader:login')

def register(request):
    if request.method == 'POST':
        registerForm = UserCustomRegister(request.POST)
        if registerForm.is_valid():
            registerForm.save()
            newUser = authenticate(username=registerForm.cleaned_data['username'],password=registerForm.cleaned_data['password1'])
            newUser.email = registerForm.cleaned_data['email']
            CommonUser(user=newUser,name=registerForm.cleaned_data['name'],
                cate=registerForm.cleaned_data['cate'],
                faculty=registerForm.cleaned_data['faculty']).save()
            login(request,newUser)
            return redirect('grader:index')
    else:
        registerForm = UserCustomRegister
    content = {'registerForm':registerForm}
    return render(request,'register.html',content)

# 用户查看个人信息，需要先登录
@login_required(login_url='grader:login')
def userCentre(request):
    # 修改个人信息
    if request.method == 'POST':
        changeForm = UserCustomChange(request.POST, instance=request.user)
        if changeForm.is_valid():
            changeForm.save()
            request.user.commonuser.name = changeForm.cleaned_data['name']
            request.user.commonuser.save()
    else:
        pass
    changeForm = UserCustomChange()
    content = {'currentUser': request.user, 'changeForm': changeForm}
    return render(request, 'userCentre.html', content)

# 用户修改密码
@login_required(login_url='grader:login')
def changePassword(request):
    if request.method == 'POST':
        changepasswordForm = PasswordChangeForm(data=request.POST, user=request.user)
        if changepasswordForm.is_valid():
            changepasswordForm.save()
            return redirect('grader:userlogin')
    else:
        pass
    changepasswordForm = PasswordChangeForm(user=request.user)
    content = {
        'currentUser': request.user,
        'changepasswordForm': changepasswordForm
    }
    return render(request, 'changePassword.html', content)

# 用户信息界面
def userInfo(request):
    return render(request, 'usr_info.html')

def index(request):
    questions_list = Question.objects.order_by('set')
    context = {
        'questions_list': questions_list,
    }
    return render(request, 'grader/index.html', context)

def essay(request, question_id, essay_id):
    essay = get_object_or_404(Essay, pk=essay_id)
    enessay = essay.content
    wcount = en_word_count(enessay)
    pcount = para_count(enessay)
    words = en_word(enessay)
    context = {
        "essay": essay,
        'wcount': wcount,
        'pcount': pcount,
        'words': words,
    }
    return render(request, 'grader/essay.html', context)

def question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AnswerForm(request.POST)

        if form.is_valid():

            content = form.cleaned_data.get('answer')

            if len(content) > 20:
                num_features = 300
                model = word2vec.KeyedVectors.load_word2vec_format(os.path.join(current_path, "deep_learning_files/word2vec.bin"), binary=True)
                clean_test_essays = []
                clean_test_essays.append(essay_to_wordlist( content, remove_stopwords=True ))
                testDataVecs = getAvgFeatureVecs( clean_test_essays, model, num_features )
                testDataVecs = np.array(testDataVecs)
                testDataVecs = np.reshape(testDataVecs, (testDataVecs.shape[0], 1, testDataVecs.shape[1]))

                lstm_model = get_model()
                lstm_model.load_weights(os.path.join(current_path, "deep_learning_files/final_lstm.h5"))
                preds = lstm_model.predict(testDataVecs)

                if math.isnan(preds):
                    preds = 0
                else:
                    preds = np.around(preds)

                if preds < 0:
                    preds = 0
                if preds > question.max_score:
                    preds = question.max_score
            else:
                preds = 0

            K.clear_session()
            essay = Essay.objects.create(
                content=content,
                question=question,
                score=preds,
                submitter=request.user.id
            )
        return redirect('grader:essay', question_id=question.set, essay_id=essay.id)
    else:
        form = AnswerForm()

    context = {
        "question": question,
        "form": form,
    }
    return render(request, 'grader/question.html', context)

# 关于界面，只接受get请求
def about(request):
    if request.method == 'GET':
        docList = Doc.objects.all()  # 文件信息
        return render(request, 'about.html', locals())

# 文件资料下载
def download_file(request, doc_id):
    # 获取资料信息用户显示
    if request.method == 'GET':
        file_result = Doc.objects.filter(id=doc_id)
        if file_result:
            file = list(file_result)[0]
            ip = 'http://127.0.0.1:8000/media/'
            path = ip + str(file.file_obj)

            # 下载资料
            try:
                response = FileResponse(requests.get(path, stream=True))
            except requests.exceptions.ConnectionError as e:
                response.status_code = '链接请求失败'
            file_ext = path.split(".")[-1]
            if not file_ext:
                pass
            else:
                file_ext = file_ext.lower()
            response['Content-Type'] = 'application/octet-stream'
            FileName = escape_uri_path(path).split('/')[-1]
            response['Content-Disposition'] = 'attachment;filename="{0}"'.format(FileName)
            return response
        else:
            return HttpResponse("文件不存在")

def file2txt(request):
    result = ''
    if request.method == "POST":
        form = RawEssaysForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        path = os.path.abspath(os.path.join(os.path.dirname(__file__),os.path.pardir))
        filepath = path + "/media/RawEssays/"
        filename = os.listdir(filepath)[0]
        ext = filename.split('.')[-1].lower()
        if ext not in ["txt", "doc", "docx", "pdf", "jpg", "jpeg", "png"]:
            result = '请上传txt, doc/docx, pdf, jpg, jpeg, png类型的文件！'
        else:
            if ext == 'txt':
                result = txt2string(filepath+filename)
            if ext in ['doc', 'docx']:
                readpath = filepath+filename
                savepath = filepath+"res.txt"
                change_word_to_txt(readpath,savepath)
                result = txt2string(savepath)
            if ext in ["jpg", "jpeg", "png"]:
                ocr = OCRrecognition()
                res = ocr.ocr(filepath+filename)[0]
                for item in res:
                    item = item[1][0]
                    result += item + '\n'
            if ext == 'pdf':
                pdf_path = filepath+filename
                img_path = filepath
                pdf2img(pdf_path,img_path)
                pdf2img(pdf_path,img_path)
                ocr = OCRrecognition()
                for i in next_png(img_path):
                    res = ocr.ocr(i)[0]
                    for item in res:
                        item = item[1][0]
                        result += item + '\n'
        delete_files(filepath)
    else:
        form = RawEssaysForm()

    return render(request, 'grader/file2txt.html', {'form': form,
                                                    'result': result,})
def chinese(request):
    if request.method == 'POST':
        form = ChineseForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            chinese = Chinese.objects.create(
                title=title,
                content=content,
                logic_score=100,
                topic_score=100,
                submitter=request.user.id
            )
        return redirect('grader:zhessay', chinese_id=chinese.id)
    else:
        form = ChineseForm()
    context = {
        "form":form,
    }
    return render(request, 'grader/chinese.html', context)

def zhessay(request, chinese_id):
    essay = get_object_or_404(Chinese, pk=chinese_id)
    zhessay = essay.content
    wcount = zh_word_count(zhessay)
    pcount = para_count(zhessay)
    words = zh_word(zhessay)
    context = {
        "essay": essay,
        'wcount': wcount,
        'pcount': pcount,
        'words': words,
    }

mysite/grader/templates/grader/chinese.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
 中文作文评分
{% endblock %}

{% block main_block %}
    <div class="container">
      <ol class="breadcrumb my-4">
          <li class="breadcrumb-item active"><a href="{% url 'grader:index' %}">切换英文作文评分</a></li>
      </ol>
    </div>
    <h1>中文作文上传</h1>
    <div>
        <a href={% url 'grader:file2txt' %}>
            上传本地作文
        </a>
    </div>
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">提交</button>
    </form>
{% endblock %}

mysite/grader/templates/grader/essay.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block main_block %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item active"><a href="{% url 'grader:index' %}">主页</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'grader:question' essay.question.set %}">作文题目 {{ essay.question.set }}</a></li>
            <li class="breadcrumb-item active">文章</li>
        </ol>
    <div class="jumbotron">
        <h1 class="display-4">分数： {{ essay.score }}/{{essay.question.max_score}}</h1>
        <p class="lead">恭喜！本作文题目的满分是： {{ essay.question.max_score }}</p>
        <hr class="my-4">
        <p>你的作文分数由AES作文评分系统给出，仅供参考！</p>
        <a class="btn btn-primary btn-lg" href="{% url 'grader:question' essay.question.set %}" role="button">重新提交作文</a>
    </div>

    <div class="container">
            <h2 class="display-4">你的作文内容：</h2>
            <p class="text-justify">{{ essay.content }}</p>
    </div>
    </div>
    <canvas id="myChart" width="400" height="400"></canvas>
    <script src="https://cdn.staticfile.net/Chart.js/3.9.1/chart.js"></script>
    <script>
    const ctx = document.getElementById('myChart');
    const data = {
    labels: [
        '词汇丰富度',
        '段落数',
        '分数',
        '字数'
    ],
    datasets: [{
        label: '英文作文分析评价',
        data: [{{ wcount }}, {{ pcount }}, {{essay.score}}, {{ words }}],
        fill: true,
        backgroundColor: 'rgba(255, 99, 132, 0.2)',
        borderColor: 'rgb(255, 99, 132)',
        pointBackgroundColor: 'rgb(255, 99, 132)',
        pointBorderColor: '#fff',
        pointHoverBackgroundColor: '#fff',
        pointHoverBorderColor: 'rgb(255, 99, 132)'
    }, {
    label: '最高分',
    data: [100, 100, {{essay.question.max_score}}, 100],
    fill: true,
    backgroundColor: 'rgba(54, 162, 235, 0.2)',
    borderColor: 'rgb(54, 162, 235)',
    pointBackgroundColor: 'rgb(54, 162, 235)',
    pointBorderColor: '#fff',
    pointHoverBackgroundColor: '#fff',
    pointHoverBorderColor: 'rgb(54, 162, 235)'
    }]
    };
    const config = {
    type: 'radar',
    data: data,
    options: {
        responsive: false, // 设置图表为响应式，根据屏幕窗口变化而变化
        maintainAspectRatio: false,// 保持图表原有比例
        elements: {
        line: {
            borderWidth: 3 // 设置线条宽度
        }
        },
        scales:{
            r:{
                suggestedMin:30,
                suggestedMax:50
            }
        }
    }
    };
    const myChart = new Chart(ctx, config);
    </script>
{% endblock %}

mysite/grader/templates/grader/file2txt.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
 英文作文评分
{% endblock %}

{% block main_block %}
    <div class="container">
      <ol class="breadcrumb my-4">
          <li class="breadcrumb-item active"><a href="{% url 'grader:index' %}">主页</a></li>
          <li class="breadcrumb-item active"><a href="#" onclick="javascript :history.go(-1);">返回作文提交页</a></li>
      </ol>
    </div>
    <form action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-info form-control " type="submit" value="submit">上传</button>
    </form>
    <div><br>作文内容识别结果：</div>
    <textarea id="result" cols="145">{{ result }}</textarea>
{% endblock %}

mysite/grader/templates/grader/index.html
{% extends 'base.html' %}

{% block title %}
 英文作文
{% endblock %}

{% block main_block %}
    {% if questions_list %}
        <p class="h3">请选择想要评分的作文题目！</p>
{#        <!-- <ul>#}
{#            {% for question in questions_list %}#}
{#            <li><a href="/{{ question.set }}">Question Set {{ question.set }}</a></li>#}
{#            {% endfor %}#}
{#        </ul> -->#}
        <table class="table">
                <thead>
                  <tr>
                    <th scope="col">序号</th>
                    <th scope="col">作文题目</th>
                    <th scope="col">最低分</th>
                    <th scope="col">最高分</th>
                  </tr>
                </thead>
                {% for question in questions_list %}
                    <tr class="clickable-row" data-href='/{{ question.set }}'>
                        <th scope="row">{{ question.set }}</th>
                        <td>{{ question.question_title|truncatewords:15 }}</td>
                        <td>{{ question.min_score }}</td>
                        <td>{{ question.max_score }}</td>
                      </tr>
                {% endfor %}
                <tbody>
                </tbody>
        </table>

        <style type="text/css">
            tr:hover {
                background-color: #cc99ff;
                cursor: pointer;
            }
        </style>


{#        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>#}
        <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
        <script>
            jQuery(document).ready(function($) {
            $(".clickable-row").click(function() {
                window.location = $(this).data("href");
            });
        });
        </script>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

mysite/grader/templates/grader/question.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
 英文作文评分
{% endblock %}

{% block main_block %}
    <div class="container">
      <ol class="breadcrumb my-4">
          <li class="breadcrumb-item active"><a href="{% url 'grader:index' %}">主页</a></li>
          <li class="breadcrumb-item active">题目 {{ question.set }}</li>
      </ol>
    </div>
{% if question %}
    <h1>作文题目 {{ question.set }}</h1>
    <p class="text-justify">{{ question.question_title }}</p>
    <div>
        <a href={% url 'grader:file2txt' %}>
            上传本地作文
        </a>
    </div>
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">提交</button>
    </form>
{% else %}
    <h1>发生错误！</h1>
{% endif %}
{% endblock %}

mysite/grader/templates/grader/zhessay.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block main_block %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item active"><a href="{% url 'grader:chinese' %}">主页</a></li>
{#            <li class="breadcrumb-item active"><a href="{% url 'grader:question' essay.question.set %}">作文题目 {{ essay.question.set }}</a></li>#}
            <li class="breadcrumb-item active">文章</li>
        </ol>
    <div class="jumbotron">
{#        <h1 class="display-4">分数： {{ essay.score }}/{{essay.question.max_score}}</h1>#}
{#        <p class="lead">恭喜！本作文题目的满分是： {{ essay.question.max_score }}</p>#}
        <hr class="my-4">
        <p>你的作文分数由AES作文评分系统给出，仅供参考！</p>
        <a class="btn btn-primary btn-lg" href="{% url 'grader:chinese' %}" role="button">重新提交作文</a>
    </div>

    <div class="container">
            <h2 class="display-4">你的作文内容：</h2>
            <p class="text-justify">{{ essay.content }}</p>
    </div>
    </div>
    <canvas id="myChart" width="400" height="400"></canvas>
    <script src="https://cdn.staticfile.net/Chart.js/3.9.1/chart.js"></script>
    <script>
    const ctx = document.getElementById('myChart');
    const data = {
    labels: [
        '词汇丰富度',
        '段落数',
        '连贯度',
        '切题度',
        '字数'
    ],
    datasets: [{
        label: '英文作文分析评价',
        data: [{{ wcount }}, {{ pcount }}, {{essay.logic_score}}, {{ essay.topic_score }}, {{ words }}],
        fill: true,
        backgroundColor: 'rgba(255, 99, 132, 0.2)',
        borderColor: 'rgb(255, 99, 132)',
        pointBackgroundColor: 'rgb(255, 99, 132)',
        pointBorderColor: '#fff',
        pointHoverBackgroundColor: '#fff',
        pointHoverBorderColor: 'rgb(255, 99, 132)'
    }, {
    label: '最高分',
    data: [100, 100, 100, 100, 100],
    fill: true,
    backgroundColor: 'rgba(54, 162, 235, 0.2)',
    borderColor: 'rgb(54, 162, 235)',
    pointBackgroundColor: 'rgb(54, 162, 235)',
    pointBorderColor: '#fff',
    pointHoverBackgroundColor: '#fff',
    pointHoverBorderColor: 'rgb(54, 162, 235)'
    }]
    };
    const config = {
    type: 'radar',
    data: data,
    options: {
        responsive: false, // 设置图表为响应式，根据屏幕窗口变化而变化
        maintainAspectRatio: false,// 保持图表原有比例
        elements: {
        line: {
            borderWidth: 3 // 设置线条宽度
        }
        },
        scales:{
            r:{
                suggestedMin:30,
                suggestedMax:50
            }
        }
    }
    };
    const myChart = new Chart(ctx, config);
    </script>
{% endblock %}